### ISSUE TITLE
example "Deploy espaloma 0.2.0" breaks

### ISSUE THREAD

**Issue by micaela-matta** [choderalab/espaloma#158] opened 2023-06-29 15:09 UTC
Hi there,

After following the [installation instructions ](https://espaloma.wangyq.net/install.html) and trying to run this same [example code snippet](https://espaloma.wangyq.net/deploy.html):

```
molecule = Molecule.from_smiles("CN1C=NC2=C1C(=O)N(C(=O)N2C)C") 
molecule_graph = esp.Graph(molecule)
espaloma_model = torch.load("/Users/micaela/Downloads/espaloma-0.2.2.pt")
```
I get the following error:

```
Cell In[11], line 1
----> 1 espaloma_model(molecule_graph.heterograph)

File ~/mambaforge/envs/espaloma-test/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/mambaforge/envs/espaloma-test/lib/python3.10/site-packages/torch/nn/modules/container.py:217, in Sequential.forward(self, input)
    215 def forward(self, input):
    216     for module in self:
--> 217         input = module(input)
    218     return input

File ~/mambaforge/envs/espaloma-test/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/mambaforge/envs/espaloma-test/lib/python3.10/site-packages/espaloma-0.3.0+12.g63ae6c6-py3.10.egg/espaloma/nn/sequential.py:143, in Sequential.forward(self, g, x)
    140 if x is None:
    141     # get node attributes
    142     x = g.nodes["n1"].data["h0"]
--> 143     x = self.f_in(x)
    145 # message passing on homo graph
    146 x = self._sequential(g_, x)

File ~/mambaforge/envs/espaloma-test/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/mambaforge/envs/espaloma-test/lib/python3.10/site-packages/torch/nn/modules/container.py:217, in Sequential.forward(self, input)
    215 def forward(self, input):
    216     for module in self:
--> 217         input = module(input)
    218     return input

File ~/mambaforge/envs/espaloma-test/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File ~/mambaforge/envs/espaloma-test/lib/python3.10/site-packages/torch/nn/modules/linear.py:114, in Linear.forward(self, input)
    113 def forward(self, input: Tensor) -> Tensor:
--> 114     return F.linear(input, self.weight, self.bias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (24x114 and 117x128)
```

I have tried the above from both an M1 laptop (via rosetta) and an Intel iMac  with identical outcome in this environment:

```
name: espaloma-test
channels:
  - conda-forge
  - dglteam
  - openeye
dependencies:
  # Base dependencies
  - python
  - pip
  # 3rd party
  - openeye-toolkits
  - numpy
  - matplotlib
  - scipy
  - openff-toolkit >=0.12
  - openff-forcefields
  - openff-units
  - ambertools >=20
  - smirnoff99Frosst
  - openmm
  - openmmforcefields >=0.11.2
  - tqdm
  # Pytorch
  - pytorch>=1.8.0
  - dgl =0.9.0
  # Testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-randomly
  - codecov
  - nose
  - nose-timer
  - coverage
  - qcportal>=0.15.0
  - sphinx
  - sphinx_rtd_theme
```

**Comment by Guackkk** [comment] 2023-06-30 10:26
I had the same error before, you can try to use the latest version 0.3.0 of espaloma. Hope it is useful to you !

**Comment by mikemhenry** [comment] 2023-07-21 15:28
Yes I recommend using the newest release of espaloma. You can install it with `$ conda install -c conda-forge -c dglteam "espaloma=0.3.1" "dgl<1"` 

Let me know if you have any other issues and if this fixes your problem, let me know :smile:

**Comment by jarvist** [comment] 2023-07-26 16:01
Following the latest conda installation instructions, as echo'd by @mikemhenry above, on a clean Conda / amd64 Linux, results in the following failure when importing espaloma:
```
; conda install -c conda-forge -c dglteam "espaloma=0.3.1" "dgl<1"
...
; python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import torch
>>> import espaloma as esp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jarvist/miniconda3/envs/openff/lib/python3.10/site-packages/espaloma/__init__.py", line 6, in <module>
    from . import metrics, units, data, app, graphs, mm, nn
  File "/home/jarvist/miniconda3/envs/openff/lib/python3.10/site-packages/espaloma/data/__init__.py", line 2, in <module>
    from . import dataset, md, normalize, utils, qcarchive_utils, md17_utils
  File "/home/jarvist/miniconda3/envs/openff/lib/python3.10/site-packages/espaloma/data/qcarchive_utils.py", line 8, in <module>
    import qcportal as ptl
  File "/home/jarvist/miniconda3/envs/openff/lib/python3.10/site-packages/qcportal/__init__.py", line 5, in <module>
    from . import collections, data, models, util
  File "/home/jarvist/miniconda3/envs/openff/lib/python3.10/site-packages/qcportal/collections/__init__.py", line 6, in <module>
    from .dataset import Dataset
  File "/home/jarvist/miniconda3/envs/openff/lib/python3.10/site-packages/qcportal/collections/dataset.py", line 14, in <module>
    from qcelemental import constants
  File "/home/jarvist/miniconda3/envs/openff/lib/python3.10/site-packages/qcelemental/__init__.py", line 6, in <module>
    from . import covalent_radii, models, molparse, molutil, periodic_table, physical_constants, util, vanderwaals_radii
  File "/home/jarvist/miniconda3/envs/openff/lib/python3.10/site-packages/qcelemental/covalent_radii.py", line 9, in <module>
    from .datum import Datum, print_variables
  File "/home/jarvist/miniconda3/envs/openff/lib/python3.10/site-packages/qcelemental/datum.py", line 12, in <module>
    class Datum(BaseModel):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
TypeError: Argument 'bases' has incorrect type (expected list, got tuple)
```

**Comment by ijpulidos** [comment] 2023-07-31 20:10
@jarvist I cannot reproduce the issue, by creating a new fresh environment using the instructions provided by @mikemhenry (changing `conda` with `mamba` since mamba solves dependencies faster) I can import espaloma just fine. Just in case it helps I'm uploading my environment file just in case it helps.
[espaloma-test-env.txt](https://github.com/choderalab/espaloma/files/12221717/espaloma-test-env.txt)

**Comment by mikemhenry** [comment] 2023-07-31 20:36
@jarvist That issue is coming fron pydantic, there was a 2.0 release lately that broke packages that didn't have a pin <2, it looks like that error is coming from `qcelemental` so try this:

`conda install -c conda-forge -c dglteam "espaloma=0.3.1" "dgl<1" "pydantic<2"`

**Comment by mikemhenry** [comment] 2023-07-31 20:37
Let me know if that resolves your issue!

**Comment by jarvist** [comment] 2023-07-31 20:45
Thanks @ijpulidos and @mikemhenry ! 
From a clean Conda environment, this time Pedantic 1.10.12 was pulled in. Espaloma imports now!

**Comment by ijpulidos** [comment] 2023-08-02 05:12
Closing this issue as resolved. Feel free to re-open as needed.

**Closed by ijpulidos** 2023-08-02 05:12 UTC
Labels: question :question:
